#prombench cluster config
zone: {{ .ZONE }}
cluster:
  name: {{ .CLUSTER_NAME }}
  initialclusterversion: 1.10.4-gke.2
  nodepools:
  # These node-pools will be deployed on triggering benchmark
  # isolation: prometheus & none will be used to differentiate them from cluster's node-pool
  - name: prometheus-{{ .PR_NUMBER }}
    initialnodecount: 2
    config:
      machinetype: n1-standard-1
      imagetype: COS
      disksizegb: 100
      localssdcount: 1  #SSD is used to give fast-lookup to Prometheus servers being benchmarked
      labels:
        isolation: prometheus
  - name: nodes-{{ .PR_NUMBER }}
    initialnodecount: 1
    config:
      machinetype: n1-standard-2
      imagetype: COS
      disksizegb: 100
      localssdcount: 0  #SSD not needed for fake-webservers (has lesser disk operations)
      labels:
        isolation: none